name: Auto Release & Build
on:
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  
jobs:
  releases-matrix:
    name: Moo Builder
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux]
        goarch: [amd64]

    steps:
    - uses: actions/checkout@v3
    - id: remote
      uses: pozetroninc/github-action-get-latest-release@v0.7.0
      with:
        repository: chdb-io/chdb
    - run:
        echo ${{ steps.remote.outputs.release }}
    - id: local
      uses: pozetroninc/github-action-get-latest-release@v0.7.0
      with:
        repository: ${{ github.repository }}
    - name: Create New Release ${{ steps.remote.outputs.release }}
      if: ${{ steps.remote.outputs.release == steps.local.outputs.release }}
      id: create_release
      uses: actions/create-release@v2.0.5
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
      with:
          tag_name: ${{ steps.remote.outputs.release }}
          release_name: ${{ steps.remote.outputs.release }}
          body: |
            ## Changes
            - Update to ${{ steps.remote.outputs.release }}
          draft: false
          prerelease: true
    - name: Log in to the Container registry
      if: ${{ steps.remote.outputs.release == steps.local.outputs.release }}
      uses: docker/login-action@v2.1.0
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Extract metadata (tags, labels) for Docker
      if: ${{ steps.remote.outputs.release == steps.local.outputs.release }}
      id: meta
      uses: docker/metadata-action@v4.3.0
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

    - name: Build and push Docker image
      if: ${{ steps.remote.outputs.release == steps.local.outputs.release }}
      uses: docker/build-push-action@v4.0.0
      with:
        context: .
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
