on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch: # on button click

permissions:
   contents: write
   pull-requests: write

jobs:
  sync_latest_from_upstream:
    runs-on: ubuntu-latest
    name: Sync with upstream
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Pull (Fast-Forward) upstream changes
      id: sync
      uses: aormsby/Fork-Sync-With-Upstream-action@v3.4
      with:
        upstream_repository: chdb-io/chdb
        upstream_branch: main
        target_branch: chdb
        #git_pull_args: --ff-only                    # optional arg use, defaults to simple 'pull'
        github_token: ${{ secrets.GITHUB_TOKEN }}
    - name: Check for new commits
      if: steps.sync.outputs.has_new_commits
      run: echo "New Commits pulled."
    - name: Timestamp
      run: date
        
