on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch: # on button click

permissions:
   contents: write
   pull-requests: write

jobs:
  sync_latest_from_upstream:
    runs-on: ubuntu-latest
    name: Sync with upstream
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Force resync with upstream
      id: sync
      run: |
        git config --global user.email "root@localhost"
        git config --global name "action runner"
        git clone https://github.com/chdb-io/chdb -b main --single-branch tmp_chdb
        cp -r tmp_chdb/* .
        rm -rf tmp_chdb
        git add .
        git commit -am resync
        
    - name: Sync to local branch
      uses: devops-infra/action-commit-push@master
      with:
        github_token: "${{ secrets.GITHUB_TOKEN }}"
        add_timestamp: false
        target_branch: chdb
        force: true
        commit_message: "resync"
        
